export const experiences = [
  {
    id: "conceito-maximo",
    styles: "right",
    title: "Desenvolvedor Full Stack Júnior",
    company: "Conceito Máximo",
    location: "Cajazeiras - PB",
    period: "05/2025 - Presente",
  },
  {
    id: "nova-studio",
    title: "Fundador da Nova Studio",
    company: "Nova Studio",
    location: "Missão Velha - CE",
    period: "04/2025 - Presente",
  },
  {
    id: "colmeia",
    styles: "right",
    title: "Desenvolvedor Full Stack Júnior",
    company: "Colmeia.io",
    location: "São Paulo - SP",
    period: "12/2025 - 02/2026",
  },
  {
    id: "suite-place",
    title: "Desenvolvedor Full Stack Júnior",
    company: "Suite Place",
    location: "Palmas - TO",
    period: "11/2024 - 10/2025",
  },
  {
    id: "loopis-gerente",
    styles: "right",
    title: "Gerente de Projetos",
    company: "Loopis Jr",
    location: "IFPB - Cajazeiras - PB",
    period: "03/2024 - 12/2024",
  },
  {
    id: "loopis-consultor",
    title: "Consultor",
    company: "Loopis Jr",
    location: "IFPB - Cajazeiras - PB",
    period: "01/2024 - 04/2024",
  },
  {
    id: "loopis-trainee",
    styles: "right",
    title: "Trainee",
    company: "Loopis Jr",
    location: "IFPB - Cajazeiras - PB",
    period: "08/2023 - 12/2023",
  },
];
